# Generated by Django 5.2.3 on 2025-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('releasedate', models.DateField()),
                ('url', models.URLField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
